# Generated by Django 5.2 on 2025-04-22 03:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
