# Generated by Django 5.2 on 2025-04-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_task_uid_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
