# Generated by Django 5.2 on 2025-04-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_task_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_uid',
        ),
    ]
